### ISSUE TITLE
Taxi Driver drives to destination, then struggles to actually complete trip so they keep driving in circles

### ISSUE THREAD

**Issue by FlamingChilly** [FiveM-Scripts/fs_taxi#12]
I have done multiple tests with different locations.  The taxi drives to the destination and then fails to actually stop and complete the trip, he stops and pulls off again circling the block and repeating.

**Comment by ghermans** [comment]
Thanks for your feedback, as you probably noticed in the readme file this script is still in a development stage, 

We know that this issue exist, the main cause is that the script isn't finding the correct ground coordinates from your blip.

a temporary workaround until a fix is being pushed, is to just shoot the driver; once he is dead the taxi vehicle & driver will be removed
