### ISSUE TITLE
Taxi stay at the destination

### ISSUE THREAD

**Issue by florinhangu** [FiveM-Scripts/fs_taxi#14]
Hi there,

The script is awesome, the problem is that the taxi driver/car stay where they dropped you. 
How can i change to make the taxi driver go away?

**Comment by ghermans** [comment]
Thanks for your feedback, as you probably noticed in the readme file this script is still in a development stage, 

We know that this issue exist, the main cause is that the script isn't finding the correct ground coordinates from your blip.

a temporary workaround until a fix is being pushed, is to just shoot the driver; once he is dead the taxi vehicle & driver will be removed

**Comment by florinhangu** [comment]
I did not know you know, i asumed is maybe fixed, and the issue is on my server. But anyway, the overall script is actually really great. 😇

**Comment by Raydiaa** [comment]
Has it been fixed? Or not? I love the script but the fact that the taxi stays there and doesn't disappear makes it hard to use.
