### ISSUE TITLE
Taxi Disappearing

### ISSUE THREAD

**Issue by HarryHyman** [FiveM-Scripts/fs_taxi#6]
So I press F7 to get a taxi, it arrives and I press E to get in. The moment I get in the car deletes itself?

**Comment by ghermans** [comment]
I can not reproduce this issue on 2 fresh installed instances so there must be a conflict with another script.

**Comment by HarryHyman** [comment]
I don't know, its been acting weirdly. It did it again the once, then it sorted itself out.

**Comment by ghermans** [comment]
Could you verify if you experience the same issue with the latest release?

**Comment by bastiaopm** [comment]
scripts muito bem feito gostei parabéns, só tem um pobleminhá ele as vezes ele dispara e sai batendo em tudo, isso as vezes.

**Comment by ghermans** [comment]
Closing this issue as no feedback has been provided.
@bastiaopm we only speak english

**Comment by bastiaopm** [comment]
> Então eu apertei F7 para pegar um táxi, ele chegou e eu pressionei para entrar. O momento que eu entro no carro se apaga?

se vc aperta F7 e o taxi vir, não entre ate que esteja marcado no mapa onde seu destino.

**Comment by ghermans** [comment]
@bastiaopm  as i said previously , we can only help if you ask your question in english.
